# Use root/example as user/password credentials
version: '3.1'

services:

  python:
    container_name: python
    build: .
    restart: ${RESTART}
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      amigo:
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: ${RESTART} 
    volumes:
      - ./mongodb/data:/data/db
    #ports:                         Expose theeports only when absolutely necessary
    #  - 27010:27010
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      amigo:

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: ${RESTART}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL
    depends_on:
      - mongo
    networks:
      amigo:

networks:
  amigo:
